### ISSUE TITLE
Script Not Working Anymore

### ISSUE THREAD

**Issue by pritamsw** [kishaningithub/shopify-csv-download#23]
Hi , the repo you created was working well before but now its not working properly , the data that is written is courpted or is not in correct format , it all gets combine and comes in single header only and all the data is getting mixed , can you please check it ?

![Screenshot (33)](https://github.com/kishaningithub/shopify-csv-download/assets/45659847/8ab9e30b-f4ef-4798-8f29-3b4e542a220a)

**Comment by kishaningithub** [comment]
Does this happen specifically on this site or on multiple sites ?

**Comment by pritamsw** [comment]
Hi , its happening for every site now . When we run the script the product gets downloaded but its not written properly, it was working well before 2 months . Maybe shopify have updated something, but the csv file thats generated now is always corrupt and comes in single line in header and gets mixed up . Can you please check it from your side for few shopify sites .

**Comment by pritamsw** [comment]
Hi , Have you checked it from your end ? There might be need to do some minute changes in the script .

**Comment by pritamsw** [comment]
Hi can you please share your email id , so we can discuss about this and if you can fix this I can pay some amount from my side

**Comment by kishaningithub** [comment]
kishancs46@gmail.com

**Comment by pritamsw** [comment]
Hi , Thanks for your support , the script is working good and fine , it seems to be an installation error from my side . However if EAN/GTIN code can be scraped it will be perfect.
