### ISSUE TITLE
Option names are wrong

### ISSUE THREAD

**Issue by brianhill2012** [kishaningithub/shopify-csv-download#3]
Hi, after testing, the option names are always same as option values. Could you help check and improve it? Thank you.

Option1   Name | Option1 Value | Option2 Name | Option2 Value
-- | -- | -- | --
For 1 dog | For 1 dog | US | US
For 1 dog | For 1 dog | EU | EU
For 1 dog | For 1 dog | AU | AU
For 1 dog | For 1 dog | UK | UK
For 2 dogs | For 2 dogs | US | US
For 2 dogs | For 2 dogs | EU | EU

**Comment by kishaningithub** [comment]
@brianhill2012 Did you face any problems because of this behavior?

**Comment by brianhill2012** [comment]
Yes, after uploading the downloaded data, the option name is same as the first option value. It looks very strange as error.jpg.

![error](https://user-images.githubusercontent.com/15664020/83973211-6d38c380-a917-11ea-9c0b-6844510e2e58.jpg)

**Comment by brianhill2012** [comment]
Hi, is it possible to fix this issue?
