### ISSUE TITLE
Getting error trying to run this on another shop.

### ISSUE THREAD

**Issue by Amahodeus** [kishaningithub/shopify-csv-download#6]
can anyone help me with this? i am stuck. i have no Mac so i had to ask someone on fiverr but he's getting this one error 

![BDD485C5-5DCB-44BB-8E00-F8B2ADAC816D](https://user-images.githubusercontent.com/43159509/100494387-d58b9380-3149-11eb-8c83-05ff1bdc86c2.png)

**Comment by kishaningithub** [comment]
In the above screenshot I see you have not put the URL of the Shopify site. You need to put the URL after shopify-csv-download command
